### ISSUE TITLE
Move to ipfs org for more maintainers?

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-check#22]
maybe? or add me? With #21 being a rewrite of the frontend logic I'm happy to be the maintainer for that part.

**Comment by aschmahmann** [comment]
Yep, happy to move to something like ipfs-shipyard. Not sure if that'll be a pain though. For now just adding you

**Comment by aschmahmann** [comment]
We're here in ipfs-shipyard now!
