### ISSUE TITLE
Update go-libp2p and redeploy

### ISSUE THREAD

**Issue by aschmahmann** [ipfs-shipyard/ipfs-check#26]
go-libp2p has been updated and resolved a number of issues around WSS as well as Circuit Relay v2 usage (e.g. not getting issues with trying to use transient connections for non-DCuTR data like Bitswap requests). This repo needs to be correspondingly updated and the backend redeployed.

**Comment by SgtPooki** [comment]
@aschmahmann As part of this task (are you taking this on?) can we also document the deployment process, and maybe automate it as well?

**Comment by aschmahmann** [comment]
Note: While not strictly required we may also want to update the backend to send back enough information for the user to learn that the only addresses they were reachable on were upgraded relay connections and then update the frontend to explain the tradeoffs with having a node only reachable via upgraded relay connections.

cc @laurentsenta

**Comment by 2color** [comment]
Fixed by https://github.com/ipfs-shipyard/ipfs-check/pull/35
