### ISSUE TITLE
chore: golang version consolidation

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ipfs-check#31]
the golang version used for the docker container (1.17.8) is different than the golang version in the go.mod file (1.16).

https://github.com/ipfs-shipyard/ipfs-check/blob/83979b0b5449837a8bf027ced135cc29418b7006/go.mod#L3

vs

https://github.com/ipfs-shipyard/ipfs-check/blob/83979b0b5449837a8bf027ced135cc29418b7006/Dockerfile#L1

**Comment by aschmahmann** [comment]
It's fine to update the go.mod version, but it's ok for them to not be the same. go.mod's Go version is basically the minimum Go "semantics" to use so you need to compile with Go >= the version in the go.mod file

**Comment by 2color** [comment]
Both the Docker image and the go.mod version are now 1.12

https://github.com/ipfs-shipyard/ipfs-check/blob/a5b6cf2182aba1699022a8b9e60d7110f0ebb7be/Dockerfile#L2
https://github.com/ipfs-shipyard/ipfs-check/blob/a5b6cf2182aba1699022a8b9e60d7110f0ebb7be/go.mod#L3
